version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9
    ports:
      - "5672:5672"
  producer:
    build: .
    command: [ "./producer" ]
  consumer:
    build: .
    command: [ "./consumer" ]
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
