version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9
    ports:
      - "5672:5672"
  producer:
    build: .
    command: [ "./producer" ]
  consumer:
    build: .
    command: [ "./consumer" ]
